# Generated by Django 4.1.3 on 2022-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact_delete_contactformmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='dept',
            field=models.CharField(choices=[('1', 'BİLİŞİM'), ('2', 'GRAFİK'), ('3', 'MATBAA'), ('4', 'BİLİŞİM')], default='4', max_length=2),
        ),
    ]
