# Generated by Django 4.1.3 on 2022-11-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_contact_last_name_contact_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dept',
            field=models.CharField(choices=[('1', 'BİLİŞİM'), ('2', 'GRAFİK'), ('3', 'MATBAA'), ('4', 'BİLİŞİM')], default=('1', 'BİLİŞİM'), max_length=21),
        ),
    ]
