# Generated by Django 4.1.3 on 2022-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_contact_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dept',
            field=models.CharField(choices=[('1', 'BİLİŞİM'), ('2', 'GRAFİK'), ('3', 'MATBAA'), ('4', 'BİLİŞİM')], default='1', max_length=2),
        ),
    ]
