# Generated by Django 4.1.3 on 2022-11-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_contact_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dept',
            field=models.CharField(max_length=100),
        ),
    ]
